### ISSUE TITLE
There should be a way to include external files (i.e. from CDN) in jasmine.yml

### ISSUE THREAD

**Issue by oveddan** [jasmine/jasmine-gem#135]
[Posted this in stackoverflow:](http://stackoverflow.com/questions/14945111/how-can-you-include-a-javascript-files-from-a-cdn-in-jasmine)

It doesn't seem like theres a way to include files from a cdn in Jasmine.yml

It is desirable to do this when on the page you are including the files from a cdn, you should keep the tests consistent and pull the files there from the same cdn.  

For example, how would you include the file: http://code.jquery.com/jquery-1.9.1.js, directly from the cdn, with your helpers?

**Comment by ShayanZafar** [comment]
@emrox  Your solution works on Jasmine 2.0 but does not work on Jasmine 2.1.3. any ideas is to why?

**Comment by slackersoft** [comment]
As of commit 29d77b253a53b35d82c578723b12ebae90a16e6f you should be able to just put http(s) urls in your jasmine.yml and they should be loaded correctly. This should be included in the released gem as of version 2.0.1
