### ISSUE TITLE
Jasmine server spinning.

### ISSUE THREAD

**Issue by squeedee** [jasmine/jasmine-gem#179]
Our jasmine server (jasmine-gem 2.0.0rc5) will randomly stop responding, holding the browser connection open, until we suspend and kill the process.

We are using rails 4, ruby 2.0

```
$ rake jasmine
your server is running here: http://localhost:8888/
your tests are here:         /.../spec/javascripts
your source files are here:  /...

[2013-11-18 16:53:47] INFO  WEBrick 1.3.1
[2013-11-18 16:53:47] INFO  ruby 2.0.0 (2013-06-27) [x86_64-darwin12.3.0]
[2013-11-18 16:53:47] INFO  WEBrick::HTTPServer#start: pid=49250 port=8888
^Z
[2]+  Stopped                 rake jasmine

$kill -9 %2
[2]+  Killed: 9               rake jasmine
```

**Comment by jaspermondie** [comment]
I've come across this issue when trying to run jasmine:ci on Travis CI frequently.

I was able to resolve this by switching out the web server that jasmine uses from webrick to thin and so far, I haven't experienced any hanging when running jasmine:ci.

To get it to run on thin, add the rack_options in your spec/javascripts/support/jasmine.yml:

`rack_options:`
     `server: 'thin'`

Also, add 
`gem 'thin'`
in group :development, :test in your Gemfile

Hope this helps those who are still facing this issue.
