### ISSUE TITLE
Feature request: jasmine:ci rake task filename/line number scoping

### ISSUE THREAD

**Issue by lencioni** [jasmine/jasmine-gem#234]
I would like to be able to more easily run specific Jasmine specs from the command line without having to run all of the specs. I know that there is now the `fit` and `fdescribe` features in 2.1.0 (which are great, by the way), but I still have the need for file-scoping from the command line.

Ideally, this would work just like RSpec where I can give it a file and also a line number, but I would be pleased as punch with even just the filename scoping feature.

I think that this would end up looking something like:

```bash
bundle exec rake jasmine:ci['specs/javascript/my_spec.js']
```

And with line scoping:

```bash
bundle exec rake jasmine:ci['specs/javascript/my_spec.js:1337']
```

What do you think?

**Comment by hsuh** [comment]
I would also like to see this feature to be implemented please . :)

**Comment by carpe171** [comment]
:+1:
