### ISSUE TITLE
Rails 4.2.1 missing rake jasmine task

### ISSUE THREAD

**Issue by shlima** [jasmine/jasmine-gem#238]
Hello, I was trying to upgrade my Rails application from 4.2.0 to 4.2.1.rc3 (pre-release), but all jasmine rake tasks are missing on the newer version of Rails

**Comment by slackersoft** [comment]
How does your `Gemfile` include the jasmine gem? If it's in a group, it should be included in `:development` because that's the environment that the rake tasks will run in by default.

What version of the jasmine gem are you using?

**Comment by shlima** [comment]
@slackersoft  Yes, it is included into the `development, test` group. The version of Jasmine gem is 2.2.0

**Comment by slackersoft** [comment]
It looks like this is an issue with how jasmine is detecting whether you have rails installed and pre-release versions of rails.

I'm working on a fix that should make this better going forward.

**Comment by shlima** [comment]
Big thanks :beers:
