### ISSUE TITLE
Rake jasmine:ci fails does not run any specs on Phantomjs 2.0.0

### ISSUE THREAD

**Issue by nsong-ti** [jasmine/jasmine-gem#244]
I've seen mixed messages about whether Phantomjs 2.0.0 is actually supported. Using Phantomjs 1.9.8 and Jasmine 2.3.0, everything runs fine.

Switching to Phantomjs 2.0.0, the jasmine server starts up, and I see the Phantomjs process running in 'top', but no specs are run. No errors in the output either.

**Comment by slackersoft** [comment]
We haven't testing the `jasmine:ci` rake task with phantom 2.0, but I would have expected it to probably work.

The way it works right now is:

* shell out to phantomjs executable with a script to run and arguments to pass to it
* retrieve the args from `phantom.args`
* get a webpage from `require('webpage')`
* register `onCallback` on that page
* optionally register `onConsoleMessage`
* `.open` the url that the jasmine server is running on

From what I can tell, all of this is still supported in phantom 2.0, and it doesn't look like the interfaces have changed.

I'd be happy to review a pull request that made the jasmine gem work with phantom 2.0, without breaking support for 1.9.x.

**Comment by PatrickKing** [comment]
It looks like PhantomJS 2.0.0 handles arguments a little bit differently. I was able to get my specs running with some minor changes to the javascript the gem hands to phantom, will see if I can get a pull request in soonish.
