### ISSUE TITLE
Is it possible to run jasmine tests across LAN?

### ISSUE THREAD

**Issue by cmrd-senya** [jasmine/jasmine-gem#250]
I want to run tests across LAN, so that jasmin is set up on one computer, and web browser runs on  another one. In order to do that I have to change the hostname to open port on. But it seems that hostname is hardcoded as localhost at https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/base.rb

Is there any way to do this without modifying jasmine-gem source code?

**Comment by Gerg** [comment]
You should be able to set a "Host" in the rack_options in your Jasmine.yml. Note the casing, as those options are passed directly into rack.

**Comment by cmrd-senya** [comment]
Thanks, appending
```yml
rack_options:
  Host: '0.0.0.0'
```
to jasmine.yml did the trick.
