### ISSUE TITLE
rake jasmine:ci doesn't work with rspec 3

### ISSUE THREAD

**Issue by brunoadacosta** [jasmine/jasmine-gem#252]
```
invalid argument: --color --format
Test::Unit automatic runner.
Usage: /Users/brunocosta/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec [options] [-- untouched arguments]
```

I've created a new task removing the "--color" options and received another error
```
invalid argument: -r /Users/brunocosta/desenvolvimento/locaweb/criador-de-sites/config/environment
```

**Comment by slackersoft** [comment]
What version of the jasmine gem are you using? As of 2.0, we no longer run the specs via rspec, so this shouldn't be an issue.

**Comment by brunoadacosta** [comment]
sorry 1.3.2

**Comment by slackersoft** [comment]
This is actually one of the reasons we moved away from running the jasmine specs via rspec. I'm not totally surprised that things stopped working, but we're moving away from support for 1.3 versions of jasmine. I would recommend upgrading to 2.0 or more recent if possible.

**Comment by slackersoft** [comment]
Closing this.
