### ISSUE TITLE
Legacy Jasmine with phatomjs

### ISSUE THREAD

**Issue by lfender6445** [jasmine/jasmine-gem#256]
for jasmine version 1.3.0 https://github.com/jasmine/jasmine-gem/tree/v1.3.0

I am attempting to run the following:

`JASMINE_BROWSER=phantomjs bundle exec rake jasmine:ci` but it always defaults to firefox. Is it possible to run CI specs with headless browser for this version of jasmine?

**Comment by slackersoft** [comment]
Jasmine 1.3 does not support phantomjs out of the box. It is only able to run browsers through selenium. It was such a highly sought after feature that we made it the default in 2.0. There were a number of blog posts and other articles out there that should be able help you get this working in 1.3, but it's not something we're looking to add to previous versions.

I know there are a number of breaking changes to upgrade, but we don't have the time to fully support 1.3 with feature requests at this point, so I would encourage you to upgrade to 2.0 (some [docs on the changes](https://jasmine.github.io/2.0/upgrading.html)).

Closing this. Thanks for using jasmine!
