### ISSUE TITLE
Don't know how to build task 'jasmine'

### ISSUE THREAD

**Issue by babu4** [jasmine/jasmine-gem#257]
A7543Q1D:/opt/usr/apps/cartcat/cart_app$ rake jasmine
rake aborted!
Don't know how to build task 'jasmine'
/home/anand/.rvm/gems/ruby-1.9.3-p194@cart_app/bin/ruby_executable_hooks:15:in `eval'
/home/anand/.rvm/gems/ruby-1.9.3-p194@cart_app/bin/ruby_executable_hooks:15:in `<main>'

**Comment by slackersoft** [comment]
It sounds like your environment isn't loading up the jasmine rake tasks. Can you answer a few questions for me to help debug the issue?

What version of the jasmine gem are you using?

Are you using rails?

If you're not using rails, make sure you've run the install step from the command line tool or properly required the jasmine rake task definition into your `Rakefile`

Thanks for using jasmine!

**Comment by slackersoft** [comment]
Closing this, since it sounds like the rake tasks are probably just not being loaded and we haven't heard anything else about this issue.
