### ISSUE TITLE
using rake jasmine:ci to run a specific test

### ISSUE THREAD

**Issue by herberzt** [jasmine/jasmine-gem#261]
Is there anyway to use `rake jasmine:ci` to run one specific test based on its name instead of all the tests?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using Jasmine! Closing.
