### ISSUE TITLE
rails g commands

### ISSUE THREAD

**Issue by lauravachon** [jasmine/jasmine-gem#270]
I am not sure if I am missing a plugin or something, but the commands that start "rails g" are not working for me. My rails does not seem to have a "g" option available.

$ rails g jasmine:install
Usage:
  rails new APP_PATH [options]

**Comment by slackersoft** [comment]
Looks like the `g` alias for `generate` isn't available for you. I've updated the README to spell it out since we shouldn't be relying on that.

Thanks for using Jasmine!
