### ISSUE TITLE
jasmine:ci keeps waiting for jasmine server to start with Puma 3.7

### ISSUE THREAD

**Issue by hackergil** [jasmine/jasmine-gem#279]
Hey guys. It seems like the jasmine server does not start when running Puma 3.7. Works fine on 3.6.2.

Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.1-p112), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
Waiting for jasmine server on 52891...
...
Waiting for jasmine server on 52891...
rake aborted!
jasmine server didn't show up on port 52891 after 20 seconds.

Any ideas around why this might be happening?

**Comment by basawyer** [comment]
Are you running Puma? I have seen this problem also. It seems related to #272. Jasmine will only run on the port that is in my config/puma.rb. This makes CI impossible on a random port. Looks like we both should get off Puma for now.

**Comment by spilin** [comment]
My puma.rb had this `port ENV.fetch("PORT") { 3000 }`
So this workaround worked for me `rake jasmine:ci PORT=3001`

**Comment by slackersoft** [comment]
Sounds like it might be an issue with Puma. The Jasmine gem attempts to start up a rake server and tell it what port to start on (https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/server.rb#L9).

If puma is not respecting the `Port` option that is given to `Rack::Server` theres not much we can do there. The only thing I could think of would be to explicitly set `ENV['PORT']` to the port we're trying to launch on. Seems hacky, but it might work.

I'd be happy to review a pull request to solve this issue.

**Comment by slackersoft** [comment]
Good? news... looks like Jasmine-Gem's own specs have this same problem. I'm looking into it now.

**Comment by jesseclark** [comment]
I was experimenting with adding an initializer which contained "require 'resolv-replace'" and that triggered this same error. Removing the initializer fixed the issue. Just adding this comment in case that is relevant to anyone else.
