### ISSUE TITLE
PhantomJS is abandoned, replace it with Selenium/Chrome headless

### ISSUE THREAD

**Issue by plentz** [jasmine/jasmine-gem#293]
related https://github.com/rails/rails/pull/30930/

**Comment by BrianHawley** [comment]
But be sure to keep PhantomJS support as an option, in case people have to run tests on platforms where GTK3 isn't supported, so they can't run headless Chrome/Firefox. (Yes, I'm aware that having to run tests on a platform that old is its own problem, but it happens.)

**Comment by slackersoft** [comment]
The original selenium functionality never really disappeared, just pulled out of this repo. Take a look at [jasmine_selenium_runner](https://github.com/jasmine/jasmine_selenium_runner) for real browser support. This gives users who are fine with PhantomJS and don't want the Selenium overhead the option, while still allowing users who want a real browser that option.

Hope this helps. Thanks for using Jasmine!

**Comment by rpbaltazar** [comment]
Is chrome headless supported in the end, or not?

**Comment by slackersoft** [comment]
Chrome headless is supported via the [jasmine selenium runner](https://github.com/jasmine/jasmine_selenium_runner) gem. I don't think we have great docs for how to use the _headless_ part of chrome with the selenium runner, but I would be happy to review a pull request there to update the readme with steps to configure the browser.

Hope this helps. Thanks for using Jasmine!

**Comment by jergarmar** [comment]
Thanks so much for the headless chrome example. Super helpful!
