### ISSUE TITLE
CSS file found instead of JS file

### ISSUE THREAD

**Issue by GCorbel** [jasmine/jasmine-gem#295]
I have a project with two files named `redactor.css` and `redactor.js`. When I try to load `redactor.js` it founds `redactor.css`. 

I think this is because of [this line](https://github.com/jasmine/jasmine-gem/blob/v2.8.0/lib/jasmine/asset_expander.rb#L4). When I do `Jasmine::AssetExpander::Rails4Or5AssetBundle.new.send(:context).
assets_environment.find_asset('redactor')`, it find the CSS file but if I search "redactor.js" it works.

I think it's better to search `redactor.js` first and `redactor` only if nothing is found.

What you think?

**Comment by slackersoft** [comment]
My best guess is this was necessary, at least sometimes, in older version of Rails. I would be happy to review a pull request that first checks for the full name with extension and only checks for an extensionless version if nothing from the first is returned.
