### ISSUE TITLE
Use proxy for rails server

### ISSUE THREAD

**Issue by danieltanfh95** [jasmine/jasmine-gem#297]
How would I use the jasmine server with an existing Rails app that lives on a different port? Do I need to remap the javascript files to use a different port? I tried using jasmine-rails but that does not work for me.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
