### ISSUE TITLE
Assets fail to be included for Rails 3.2.22 using genrators

### ISSUE THREAD

**Issue by jwlms** [jasmine/jasmine-gem#299]
I'm unable to get this gem working properly with Rails 3.2.22 even though the readme indicates that its supported (and it does work as expected in Rails5). 

Jasmine does work, but isn't able to include assets. This makes me think its a configuration issue with the asset pipeline not properly including the scripts in the `assets/javascripts` directory. I've attempted altering the source files in `jasmine.yml` with no luck.

#### Create a new Rails 3.2.22 app

```
$ rails new jasmine-test-app
```

#### Add the Gem
```
group :development, :test do
  gem 'jasmine'
end
```

#### Run Bundler
```
$ bundle install
```

#### Initialize and generate examples
```
rails generate jasmine:install

rails generate jasmine:examples
```

#### Run the tests
```
rake jasmine
```

#### Expected Results
`6 specs, 0 failures, randomized with seed (...)`

#### Actual Results
`6 specs, 6 failures, randomized with seed (...)`

Is this gem supported for Rails 3? Any ideas on what the issue is?

**Comment by slackersoft** [comment]
Jasmine 3.0 dropped support for Rails 3 (see the [release notes](https://github.com/jasmine/jasmine-gem/blob/master/release_notes/3.0.md)), but it doesn't look like the README was updated appropriately. Rails 3 is no longer supported by the Rails team, either.

Sorry for the confusion. Thanks for using Jasmine!

**Comment by jwlms** [comment]
Thanks for the reply and updating the readme! (I'm aware of the lack of support for Rails 3, it's just a project I've inherited).
