### ISSUE TITLE
How to use it with IstanbulJS ?

### ISSUE THREAD

**Issue by bdavidxyz** [jasmine/jasmine-gem#300]
It's becoming harder to find any up-to-date way to have JavaScript coverage in a Rails project. Teaspoon is not anymore actively maintained, so it would be nice to have a tutorial on how to integrate this gem with a standard tool like IstanbulJS. Thanks !

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
