### ISSUE TITLE
Chrome headless, TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by stoivo** [jasmine/jasmine-gem#306]
I have  a problem with my jasmine suite. I get a TypeError: Converting circular structure to JSON error.   
The error is random. I have been looking into it and found out that it is because a failure, in the result object passed to ruby contain Jquery element which can't be JSON.stringified.
https://github.com/stoivo/jasmine-gem/commit/33d0c1d5a2d3028e8dc9bffc46a21ad45532b5a6

I will submit a PR when I can confirm that is works.

The problem is that our spec is flaky and it gave the wrong message.

**Comment by slackersoft** [comment]
`JSON.stringify` is the best way we have so far to serialize the failure information from the browser into the ruby code. I'd be happy to see some kind of cycle detection in that, as long as it doesn't prove too crazy.

**Comment by stoivo** [comment]
I have having good result with a patch I use locally, I will battle test it a little more before I submit a PR.

**Comment by sgravrock** [comment]
Closing since jasmine-gem is discontinued.
